# Support for "precompiled headers"-aware compilers

FUNCTION(SET_USE_PRECOMPILED_HEADER TARGET_NAME H_NAME CPP_NAME)		# PCH_NAME
	IF(MSVC AND PVLE_USE_PRECOMPILED_HEADERS)
		GET_TARGET_PROPERTY(TEMP_PROPERTY ${TARGET_NAME} COMPILE_FLAGS)
		IF(NOT TEMP_PROPERTY)
			SET(TEMP_PROPERTY )
		ENDIF()
		SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES COMPILE_FLAGS "${TEMP_PROPERTY} /Yu\"${H_NAME}\" /FI\"${H_NAME}\"")		# /FI means "Forced include" - /Fp\"${PCH_NAME}\"

		GET_SOURCE_FILE_PROPERTY(TEMP_PROPERTY ${CPP_NAME} COMPILE_FLAGS)
		IF(NOT TEMP_PROPERTY)
			SET(TEMP_PROPERTY )
		ENDIF()
		SET_SOURCE_FILES_PROPERTIES(${CPP_NAME} PROPERTIES COMPILE_FLAGS "${TEMP_PROPERTY} /Yc\"${H_NAME}\"")	# /Fp\"${PCH_NAME}\"
	ENDIF()
ENDFUNCTION()
